apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: retail-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "31504"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: ui
    app.kubernetes.io/name: ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31504
      protocol: TCP